### ISSUE TITLE
Related approach just FYI

### ISSUE THREAD

**Issue by mikelnrd** [felixge/httpsnoop#10]
Hi 

This looks very similar in approach, just thought I'd share it with you in case it's of interest:

https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/delegator.go

Source:
I came across httpsnoop in this thread which might also be of interest if you haven't seen it:
https://github.com/golang/go/issues/18997#issuecomment-314736760

**Comment by felixge** [comment]
> https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/delegator.go

The prometheus implementation didn't exist when I wrote this library. I wonder if they were aware of my implementation and decided against using it. But it seems like this [wasn't the case](https://github.com/prometheus/client_golang/issues/272).

> https://github.com/golang/go/issues/18997#issuecomment-314736760

I agree with this thread. Having to do this kind of hacking like my lib is terrible, it'd be nice if there were better solutions!

**Comment by felixge** [comment]
Closing this since there is no more action to be taken.
