### ISSUE TITLE
Create a new release that includes the new Unwrapper API

### ISSUE THREAD

**Issue by IanChen83** [felixge/httpsnoop#15]
Currently we can only use the `Unwrapper` API by explicitly specifying the commit hash in `go.mod`. Is the API intentionally not included in the newest release ? If no, this is just a friendly reminder that a new release is missing for publishing #12 (and later PRs) :).

**Comment by felixge** [comment]
@IanChen83 I just tagged a new release: https://github.com/felixge/httpsnoop/releases/tag/v1.0.2

Let me know if this works :)
