### ISSUE TITLE
Storing values alone with the wrapped ResponseWriter for later access

### ISSUE THREAD

**Issue by IanChen83** [felixge/httpsnoop#16]
Thanks for bringing up the common pitfall of naively embedding `http.ResposeWriter` and maintaining this package as the solution before the std library updates its APIs. During the attempts of using this library in our application, I found out that a common scenario for embedding `http.RequestWriter` is to compute and store values in the middlewares so they can be accessible in the handlers or other middlewares later. With the `httpsnoop.Wrap`, this would be impossible because there's no way to store additional values (well, closure would be the only way, but the lifecycle of the variables are bounded by the outer function). Do you have any suggestion how we can achieve this?

The only approach I can think of now is to introduce a value store, possibly similar to `Context.Value`, in the hook that can be accessible in the lifecycle of the request. The API might be

```golang
if values, ok := w.(httpsnoop.Values); ok {
  // values could be map[string]interface{}, http.Values, or custom types.
}

```

Do you think that would be a good addon to the existing APIs ?

**Comment by felixge** [comment]
Let me make sure I understand the issue correctly: You got some middleware in your app that wraps a http writer in something like this?

```go
struct myHttpWriter {
  http.RequestWriter
  extraField string
}
```

And then you'd like to use `httpsnoop.Wrap()` to wrap it, and then still be able to get a reference to `myHttpWriter` so you can access `extraField`?

I think the [Unwrap()](https://pkg.go.dev/github.com/felixge/httpsnoop?utm_source=godoc#Unwrap) will let you do this, but it seems like you've [already discovered it](https://github.com/felixge/httpsnoop/issues/15) so perhaps I'm not fully understanding the situation.

**Comment by IanChen83** [comment]
Sorry if the description is not clear enough. Let me provide an example. Assume that we want to access the response body in multiple middlewares but we don't want to duplicate the writer multiple times. If I understand correctly, defining a struct like

```golang
type myResponseWriter struct {
  http.RequestWriter
  buf bytes.Buffer
}
```

and wrapping it with `httpsnoop.Wrap()` won't work because it will return an `http.ResponseWriter` with only `Header()`, `Write()` and `WriteHeader()` functions ([the first case in `Wrap()`](https://github.com/felixge/httpsnoop/blob/42c30f944879059639bcf7b2ca4aba06f4a83198/wrap_generated_gteq_1.8.go#L74-L79)). This implies the input `ResponseWriter` of `httpsnoop.Wrap` must directly come from the upstream writer, and the input of `next` must come from `httpsnoop.Wrap`, as shown below

```golang
func middleware(next http.Handler) http.Handler {
  // ... the begining of variable lifecycle
  return func(w http.ResponseWriter, r *http.Request) {
    // ...
    next(httpsnoop.Wrap(w, hooks), r)
    // post processing
  }
}
```

So I'm wondering if it's a good idea to carry additional values in the `http.ResponseWriter` returned by `httpsnoop.Wrap`, which could be implemented by introducing a new method in the wrapped `ResponseWriter` that could be extracted with  type checking.

```golang
if valuer, ok := w.(httpsnoop.Valuer); ok {
  // valuer.Set(k, v), valuer.Get(k) v
}
```

**Comment by IanChen83** [comment]
An obvious solution would be storing the values in the request's context. But people using this library must have rejected this idea; otherwise they won't have to use this library in the first place ...

**Comment by felixge** [comment]
@IanChen83 I'm afraid I'm still lost. Here is an example of using `Unwrap()` to access `myResponseWriter` after it's been wrapped by a middleware. Isn't that what you're trying to do?

```go
func TestGH16(t *testing.T) {
	type myResponseWriter struct {
		http.ResponseWriter
		buf *bytes.Buffer
	}

	middleware := func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			buf := bytes.NewBuffer([]byte("hello world"))
			mw := myResponseWriter{w, buf}
			wrapped := Wrap(mw, Hooks{})
			next.ServeHTTP(wrapped, r)
		})
	}

	middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		unwrapped := Unwrap(w).(myResponseWriter)
		if unwrapped.buf.String() != "hello world" {
			t.Fatal("unwrapping did not work")
		}
	})).ServeHTTP(httptest.NewRecorder(), nil)
}
```
