### ISSUE TITLE
Support 1xx headers

### ISSUE THREAD

**Issue by mitar** [felixge/httpsnoop#23]
Go 1.19 gained support for [103 Early hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103) (https://github.com/golang/go/pull/42597). The implementation of HTTP server changed to allow for 1xx headers so now a common way to set them is to set headers and then call `WriteHeader(StatusEarlyHints)` which then allows setting more headers and then call do regular response writing, calling `WriteHeader` again, or just calling `Write`.

From looking around a bit around code here, I think `CaptureMetrics` might not work correctly, as it assumes `WriteHeader` is written only once. I can make a PR to fix that.

But I am not sure about any other breakage which might be happening because of that change. Anything?

**Comment by mitar** [comment]
I made https://github.com/felixge/httpsnoop/pull/24.

**Comment by felixge** [comment]
https://github.com/felixge/httpsnoop/pull/24 is merged.
