### ISSUE TITLE
Not possible to get w.(httpPusher)

### ISSUE THREAD

**Issue by krusche-company** [felixge/httpsnoop#3]
Hi, I am using http2 server (go1.8) with your library. But seems responseWriter is changed, so I can not get w.(httpPusher) and use http2 Push feature

**Comment by felixge** [comment]
Yeah, I'll need to add support for the new interface to this library. I'll try to get to it very soon. But I'd also be happy to accept a patch if somebody beats me to it :)

**Comment by felixge** [comment]
@krusche-company this turned out to be quite a little effort, but I think it turned out nicely. Please try the latest version and let me know how it goes.
