### ISSUE TITLE
Tag versioned releases

### ISSUE THREAD

**Issue by akshayjshah** [felixge/httpsnoop#7]
Hi! I notice that this project doesn't have any [tagged releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases). Would you mind adding some [SemVer](http://semver.org/)-compatible release tags? It would really, really help those of us using [`dep`](http://github.com/golang/dep) and similar tools.

**Comment by felixge** [comment]
Not sure how I missed this, but here you go: https://github.com/felixge/httpsnoop/releases/tag/v1.0.0

**Comment by akshayjshah** [comment]
Thanks! 😍

**Comment by hypnoglow** [comment]
Hey @felixge , I don't want to start a new issue, but can you tag a new versioned release? There are quite some changes since 24 Jan. What do you think?

**Comment by felixge** [comment]
@hypnoglow Are you sure? v1.0.0 points at eadd4fa which is the HEAD of master.
