### ISSUE TITLE
Ability to access the wrapped ResponseWriter

### ISSUE THREAD

**Issue by pda** [felixge/httpsnoop#8]
Thanks for the library.

It would be useful to be able to explicitly access the underlying ResponseWriter.

For example New Relic's go-agent implements their `newrelic.Transaction` as an extension of `http.ResponseWriter`. I'd like to write middleware which type-asserts `txn, ok := w.(newrelic.Transaction)` in order to e.g. `txn.AddAttribute()`. But when `w` is already wrapped in `httpsnoop` the `newrelic.Transaction` type-assertion fails. I guess this is a case you've described in the README as “and it won't work for applications adding their own interfaces into the mix”.

However I'd be happy to do something like this:

```go
if snoop, ok := w.(httpsnoop.Wrapper) {
  if txn, ok := snoop.Unwrap().(newrelic.Transaction) {
    txn.SetAttribute("foo", "bar")
  }
}
```

This would require a method on httpsnoop's `type rw` e.g. `rw.Unwrap()` or `rw.ResponseWriter()`, and an interface containing that method (although the caller could be responsible for declaring the interface).

(The httpsnoop assertion may need to be recursive in case it's wrapped multiple times; e.g. a request that has passed through a logging middleware _and_ a metrics middleware that each use httpsnoop. But that's up to the caller).

Perhaps the patch would be something like this?

```patch
--- a/codegen/main.go
+++ b/codegen/main.go
@@ -127,6 +127,14 @@ type rw struct {
        w http.ResponseWriter
        h Hooks
 }
+
+type Wrapper interface {
+       Unwrap() http.ResponseWriter
+}
+
+func (w *rw) Unwrap() http.ResponseWriter {
+       return w.w
+}
 `)
        for _, iface := range ifaces {
                for _, fn := range iface.Funcs {
```

**Comment by felixge** [comment]
@pda that seems totally reasonable. If you want to send a PR with the patch above I'll merge it. Only nitpick is to maybe call the interface `Unwrapper`.

**Comment by basvanbeek** [comment]
how about also adding a convenience helper function that unwraps the original interface in case w is httpsnoop and returns w unmodified if not. This would allow: 
```go
if txn, ok := httpsnoop.Unwrap(w).(newrelic.Transaction) {
  txn.SetAttribute("foo", "bar")
}
```

**Comment by felixge** [comment]
@basvanbeek I guess I like that even better :)

**Comment by matthewmueller** [comment]
I took a crack at this with a slightly different approach: https://gist.github.com/matthewmueller/d2eb103a2cd98abfcf6ecdfceb993374

My use case is to allow HTTP headers to be set in middleware without needing to be extra cautious to avoid `Write` and `WriteHeader` "committing" the response.

I was planning to PR this @felixge, but I think the `state` struct might be a bit too opinionated. I'd be curious to hear your thoughts. I think it would solve most use cases, but it doesn't seem like a general solution.

**Comment by felixge** [comment]
@matthewmueller hey, sorry for not replying yet, I'll try to take a look soon and let you know what my thoughts on your approach are.

**Comment by felixge** [comment]
@matthewmueller I just took a closer look, it seems like your solution would always buffer the entire response?

IMO that's not a reasonable default considering the additionally memory usage and latency this might introduce for some users. By default httpsnoop should introduce no noticeable overheads.

**Comment by felixge** [comment]
I've squash-landed the latest patches that were flying around for this here: https://github.com/felixge/httpsnoop/pull/12

Closing this for now, but @matthewmueller feel free to continue commenting or to open a new issue for your particular concerns.

**Comment by matthewmueller** [comment]
Sounds good. I'll give this a shot soon. Thanks @felixge!
